POST {{baseUrl}}
Content-Type: application/json

{
  "name": "duy",
  "gender": "male",
  "birthday": "2001-11-05",
  "phone": "0346750988",
  "email": "ttduy051101@gmail.com",
  "address": "hcm",
  "role": {
    "id": "08f56683-7839-4305-a26c-feedd7fd9a3f"
  },
  "company": {
    "id": "12d9a8a5-de46-42b4-9c91-aa94c745ad2b"
  }
}

###
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "duy",
  "gender": "male",
  "birthday": "2001-11-05",
  "phone": "0346150988",
  "email": "ttduy051101@gmail.com",
  "address": "hcm",
  "role": {
    "id": "b8403da5-c109-4eba-9712-67f40f2e8ef8"
  },
  "company": {
    "id": "aea734ed-8345-4d74-84e9-2d5c86a8297b"
  }
}
