POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ0NjI2MDQsImV4cCI6MTcyNDU0OTAwNH0.D6GJDES-ELmFIb9kFku3LpAGvkNV7jnPqAdl0zcDwqCQTwZrOK5XFYCm7rim8_oSMIYI8QjgcrFbFLMLH_3PGA

{
  "name": "duy",
  "gender": "male",
  "birthday": "2001-11-05",
  "phone": "0346750988",
  "email": "ttduy051101@gmail.com",
  "address": "hcm",
  "role": {
    "id": "08f56683-7839-4305-a26c-feedd7fd9a3f"
  },
  "company": {
    "id": "12d9a8a5-de46-42b4-9c91-aa94c745ad2b"
  }
}

###
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ0NjI2MDQsImV4cCI6MTcyNDU0OTAwNH0.D6GJDES-ELmFIb9kFku3LpAGvkNV7jnPqAdl0zcDwqCQTwZrOK5XFYCm7rim8_oSMIYI8QjgcrFbFLMLH_3PGA

{
  "name": "duy",
  "gender": "male",
  "birthday": "2001-11-05",
  "phone": "0346151988",
  "email": "trantuanduy.05112001@gmail.com",
  "address": "hcm",
  "role": {
    "id": "3a68854b-3970-4ec1-a36b-b0ea259712f7"
  },
  "company": {
    "id": "85b8125d-6737-42db-87ad-629b019c2a1b"
  }
}

###
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ0NjI2MDQsImV4cCI6MTcyNDU0OTAwNH0.D6GJDES-ELmFIb9kFku3LpAGvkNV7jnPqAdl0zcDwqCQTwZrOK5XFYCm7rim8_oSMIYI8QjgcrFbFLMLH_3PGA

{
  "name": "duy",
  "gender": "male",
  "birthday": "2001-11-05",
  "phone": "0346150988",
  "email": "ttduy051101@gmail.com",
  "address": "hcm",
  "role": {
    "id": "b8403da5-c109-4eba-9712-67f40f2e8ef8"
  },
  "company": {
    "id": "aea734ed-8345-4d74-84e9-2d5c86a8297b"
  }
}
