GET {{baseUrl}}
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0cmFudHVhbmR1eS4wNTExMjAwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ0OTk4MDAsImV4cCI6MTcyNDU4NjIwMH0.6Wpv9hTmkGFoJN9zjWvjv6UMZBGVpAsCRWMZx4r3m-4QwRei4pYL51iNqniRBt1Qkm7aQwnBfUm-HfNlfZMfNQ
