POST {{baseUrl}}/create_classroom_auto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ1ODUwMTQsImV4cCI6MTcyNDY3MTQxNH0.lqIhrq4aaN39sOsVYTOMcw6Ggvvx5Mh7XG1JLBZc3b5bQ--FAYuzBIMswuDqYOLaS6-P_6FuB784DZ51h3qHow

{
  "course": {
    "id": "52a69c0b-d0fc-4f64-a7eb-fbd4fbebfe65"
  },
  "size": 1
}

###
