POST {{baseUrl}}
Content-Type: application/json

{
  "name": "admin",
  "permissions": [
    {
      "id": "9fb32469-0435-40c7-a3c2-0ec23cffe415"
    }
  ]
}

###
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "admin_company",
  "permissions": [
    {
      "id": "9fb32469-0435-40c7-a3c2-0ec23cffe415"
    }
  ]
}