POST {{baseUrl}}
Content-Type: application/json

{
  "name": "admin",
  "permissions": [
    {
      "id": "4e049280-4383-474a-859c-72b01bbbfd9d"
    }
  ]
}

###
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "admin_company",
  "permissions": [
    {
      "id": "4e049280-4383-474a-859c-72b01bbbfd9d"
    }
  ]
}

###
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "teacher",
  "permissions": [
    {
      "id": "4e049280-4383-474a-859c-72b01bbbfd9d"
    }
  ]
}