POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "ttduy051101@gmail.com",
  "password": "ABCD"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "trantuanduy.05112001@gmail.com",
  "password": "8c71194af826"
}

###
POST http://localhost:8080/api/password-reset/request
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ1ODU4NTgsImV4cCI6MTcyNDY3MjI1OH0.EDugTiH4ZalzlW_2tGVuV1Rd29Z7Pq-b6L10rDw56rPJRQnHvakpLsIMdEnCH7E-FrtnJf8kAh2d0rvLQTH3dQ

