POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "ttduy051101@gmail.com",
  "password": "ABCD"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "trantuanduy.05112001@gmail.com",
  "password": "8c71194af826"
}

###
POST http://localhost:8080/api/password-reset/request
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0dGR1eTA1MTEwMUBnbWFpbC5jb20iLCJpYXQiOjE3MjQ2NDcyMTUsImV4cCI6MTcyNDczMzYxNX0.NipKa805njX7scF_s8YUKRwmQEtTK2dW8hsh_dyaMiUTp0o5mQz4ODJvXvEwJaA8JGfqS-8vf2cVoeUI-zeLVg

