### get all
GET {{baseUrl}}/
Accept: application/json

### get by id
GET {{baseUrl}}/cbbd9105-09db-432c-b8fb-950610d11dea
Accept: application/json

###
PUT {{baseUrl}}/cbbd9105-09db-432c-b8fb-950610d11dea/update_info
Content-Type: application/json

{
  "name": "IT"
}